### ISSUE TITLE
Button Not working

### ISSUE THREAD

**Issue by ghost** [synterrr/monke.io#3]

**Comment by tristencrp** [comment]
They work, they just don't work for you if you're clicking the buttons on your own account. Get on an alt discord and you could click the buttons perfectly fine. Pretty strange but it works. 🤷

**Comment by synterrr** [comment]
that's a discord thing tho

**Comment by tristencrp** [comment]
It never stated it would do that or I just didn't read the entire description (mb if so), so I was just confused.
